name: Upload Contacts JSON to S3
on:
  push:    
    branches:
      # only run when this branch is pushed to
      - json-upload

  # can run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  s3-upload:
    runs-on: ubuntu-latest

    # get runtime variables/secrets from this environmnet configuration
    environment: s3-demo-cicd
  
    #/home/runner/work/s3-demo-cicd/s3-demo-cicd
    env:
      AWS_ACCESS_KEY_ID     : ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY : ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION            : us-east-2
      S3_BUCKET             : ${{ vars.AWS_S3_TARGET }}
      SRC_FILE              : ficticious-contacts.json
      WORK_PREFIX           : /tmp
      WORK_DIR              : repo

    steps:
      # checkout the github repo onto the runner into a directory named 'repo'
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: z-tb/s3-demo-cicd
          path: $PREFIX/$WORK_DIR

      - name: list workdir
        run: find $WORK_PREFIX/$WORK_DIR -type f | grep json

      - name: upload to s3
        run: aws s3 cp ${{ env.WORK_PREFIX }}/${{ env.WORK_DIR }}/${{ env.SRC_FILE }} s3://${{ vars.AWS_S3_TARGET}}   
            

