name: Upload Contacts JSON to S3
on:
  push:    
    branches:
      - json-upload

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  s3-upload:
    runs-on: ubuntu-latest            
    env:
      MY_S3_TARGET: ${{ vars.AWS_S3_TARGET}}

    steps:
      - name: Configure my AWS Credentials
        run: echo foo
            

