name: Upload Contacts JSON to S3
on:
  push:    
    branches:
      - json-upload

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  s3-upload:
    runs-on: ubuntu-latest        
    environment: s3-demo-cicd
        
    env:
      MY_LOCAL_TARGET: "bug-bucket"

    steps:
      - name: S3 env target
        run: echo "env var is ${{ vars.AWS_S3_TARGET}}   "
      - name: S3 local target
        run: echo "local var $MY_LOCAL_TARGET"

            

