name: Upload Contacts JSON to S3
on:
  push:    
    branches:
      - json-upload

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  s3-upload:
    runs-on: ubuntu-latest            
    env:
      MY_S3_TARGET: "flalblakjsdaf"

    steps:
      - name: S3 var target
        run: echo "var is ${{ vars.AWS_S3_TARGET}}   "
      - name: S3 local target
        run: echo "env $MY_S3_TARGET"

            

