name: Upload Contacts JSON to S3
on:
  push:    
    branches:
      - json-upload

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  s3-upload:
    runs-on: ubuntu-latest            
    env:
      MY_S3_TARGET: ${{ vars.AWS_S3_TARGET}}

    steps:
      - name: S3 var target
        run: echo ${{ vars.AWS_S3_TARGET}}
      - name: S3 env target
        run: echo ${{ env.AWS_S3_TARGET}}
      - name: S3 local target
        run: echo ${{ env.MY_S3_TARGET }}

            

