name: Upload Contacts JSON to S3
on:
  push:    
    branches:
      # only run when this branch is pushed to
      - json-upload

  # can run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  s3-upload:
    runs-on: ubuntu-latest

    # get runtime variables/secrets from this environmnet configuration
    environment: s3-demo-cicd
  
    env:
      AWS_ACCESS_KEY_ID     : ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY : ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION            : ${{ vars.AWS_REGION }}
      S3_TARGET             : s3-demo-alpha-zulu
      SRC_FILE              : ficticious-contacts.json
      WORK_PREFIX           : /home/runner/work/
      WORK_DIR              : repo
      GH_REPO               : s3-demo-cicd
      GH_ACCT               : z-tb

    steps:
      # checkout the github repo onto the runner into a directory named 'repo'
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: ${{ env.GH_ACCT }}/${{ env.GH_REPO }}
          path: ${{ env.WORK_PREFIX }}/${{ env.GH_REPO }}/${{ vars.environment}}/${{ env.WORK_DIR }}

      - name: list workdir
        run: find ${{ env.WORK_PREFIX }}/${{ env.WORK_DIR }} -type f | grep json

      - name: upload to s3
        run: aws s3 cp ${{ env.WORK_PREFIX }}/${{ env.WORK_DIR }}/${{ env.SRC_FILE }} s3://${{ env.S3_TARGET}}   
            

