name: Upload Contacts JSON to S3
on:
  push:    
    branches:
      - json-upload

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest            
    env:
      S3_TARGET: ${{ vars.AWS_S3_TARGET}}
    steps:
      - name: Configure my AWS Credentials
        run: echo "s3 target is: ${{ S3_TARGET }}"
            

