name: Upload Contacts JSON to S3
on:
  push:    
    branches:
      - json-upload

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  s3-upload:
    runs-on: ubuntu-latest        
    environment: s3-demo-cicd
        
    env:
      MY_LOCAL_TARGET: "bug-bucket"
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: us-east-2
      S3_BUCKET: ${{ vars.AWS_S3_TARGET }}
      SRC_FILE: ficticious-contacts.json

    steps:
      - name: S3 env target
        run: echo "env var is ${{ vars.AWS_S3_TARGET}}   "

      - name: S3 local target
        run: echo "local var $MY_LOCAL_TARGET"
      
      - name: list workdir
        run: ls -lart ~/workdir

      - name: upload to s3
        run: aws s3 sync ${{ env.SRC_FILE }} s3://${{ vars.AWS_S3_TARGET}}   
            

