name: Upload Contacts JSON to S3
on:
  push:    
    branches:
      - json-upload

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest            
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Add a step to run the find command on /
      - name: Find Files in home dir
        run: ls -lart /home/runner/work
      
      - name: Configure my AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id    :  ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region           :  ${{ env.AWS_REGION }}
          mask-aws-account-id  : yes

            
      - name: Upload JSON to S3
        #run: aws s3 cp contacts.json s3://s3/
        run: aws s3 ls

